---

# Jenkins comes with bundled plugins that get priority during deployment. This
# means that any newer version of a bundled plugin that gets downloaded to
# ~/plugins will be ignored and replaced with the bundled version the next
# time Jenkins is restarted.
#
# A workaround is to download a newer version and pin it (create a .pinned
# file). In this case Jenkins will not atempt to overwrite the newer version.
#
# Pinning a plugin does not mean that newer versions will get ignored. The
# pluginManager will continue to check for newer version and make them avai-
# lable through the web interface.

- name: Create Jenkins auxiliary directory for holding JARs, scripts, etc
  file:
    path: "{{ jenkins_aux_dir }}"
    state: directory
    owner: root
    group: root

- name: Extract the jenkins_cli jarfile
  command: unzip -oj /usr/lib/jenkins/jenkins.war WEB-INF/jenkins-cli.jar -d /opt/jenkins/

- name: Create deploy user
  user:
    name: deploy
    state: present

- name: Create jenkins_jobs directory
  file:
    path: /home/deploy/jenkins_jobs
    state: directory
    owner: deploy

- name: Transfer jenkins-jobs configuration (missing token)
  copy:
    src: jenkins_jobs.ini
    dest: /home/deploy/jenkins_jobs.ini
    owner: deploy

- name: Configure Jenkins startup
  template:
    src: sysconfig.j2
    dest: /etc/sysconfig/jenkins
  when: not is_docker

- name: Enable and start Jenkins
  service:
    name: jenkins
    state: started
  when: not is_docker

- name: Start Jenkins (Docker)
  command: >
    su - {{ jenkins_user }}
    -c /bin/java {{ jenkins_java_options }}
    -DJENKINS_HOME={{ /var/lib/jenkins }}
    -jar /usr/lib/jenkins/jenkins.war
    --webroot=/var/cache/jenkins/war
    --httpPort={{ jenkins_port }}
    --httpListenAddress={{ jenkins_listen_address }}
    --ajp13Port=-1
    --daemon
    --debug={{ jenkins_debug_level }}
    --handlerCountMax={{ jenkins_handler_max }}
    --handlerCountMaxIdle={{ jenkins_handler_idle }}
  when: is_docker

- name: Wait for Jenkins to be ready
  shell: "curl -D - --silent http://{{ jenkins_listen_address }}:{{ jenkins_port }}/cli/"
  register: result
  until: >
    ((result.stdout.find("200 OK") != -1) or
    (result.stdout.find("Authentication required") != -1)) and
    (result.stdout.find("Please wait while") == -1)
  retries: "{{ jenkins_conn_retries }}"
  delay: "{{ jenkins_conn_delay }}"
  changed_when: false

- name: Get list of currently installed plugins (anonymous)
  shell: "java -jar {{ jenkins_cli_jar }} -s http://{{ jenkins_listen_address }}:{{ jenkins_port }}/ list-plugins | awk '{ print $1 }'"
  register: plugin_list

- name: Install additional plugins and update everything
  get_url:
    dest: "{{ jenkins_home }}/plugins/{{ item }}.jpi"
    url: "{{ jenkins_updates_url }}/latest/{{ item }}.hpi"
    force: yes
    owner: "{{ jenkins_user }}"
  when: not plugin_list.stderr
  with_items:
    - "{{ plugin_list.stdout_lines }}"
    - "{{ jenkins_plugins }}"
  notify:
    - restart jenkins

- name: Pin all plugins to avoid bundled versions getting reinstalled
  file:
    path: "{{ jenkins_home }}/plugins/{{ item }}.jpi.pinned"
    state: touch
    owner: "{{ jenkins_user }}"
  when: not plugin_list.stderr
  with_items:
    - "{{ plugin_list.stdout_lines }}"
    - "{{ jenkins_plugins }}"
  notify:
    - restart jenkins

- name: Get list of currently installed plugins (with credentials)
  shell: "java -jar {{ jenkins_cli_jar }} -s http://{{ jenkins_listen_address  }}:{{ jenkins_port }}/ list-plugins {{ jenkins_admin_credentials }} | awk '{ print $1 }'"
  register: plugin_list_credentials
  when: plugin_list.stderr

- name: Install additional plugins and update everything
  get_url:
    dest: "{{ jenkins_home }}/plugins/{{ item }}.jpi"
    url: "{{ jenkins_updates_url }}/latest/{{ item }}.hpi"
    force: yes
    owner: "{{ jenkins_user }}"
  when: plugin_list_credentials.stdout_lines is defined
  with_items:
    - "{{ plugin_list_credentials.stdout_lines }}"
    - "{{ jenkins_plugins }}"
  notify:
    - restart jenkins

- name: Pin all plugins to avoid bundled versions getting reinstalled
  file:
    path: "{{ jenkins_home }}/plugins/{{ item }}.jpi.pinned"
    state: touch
    owner: "{{ jenkins_user }}"
  when: plugin_list_credentials.stdout_lines is defined
  with_items:
    - "{{ plugin_list_credentials.stdout_lines }}"
    - "{{ jenkins_plugins }}"
  notify:
    - restart jenkins

- name: Generate temporary file
  command: /usr/bin/mktemp
  register: mktemp

- name: Transfer Groovy script used for security configuration
  template:
    src: security.gy.j2
    dest: "{{ mktemp.stdout }}"
    backup: no

- name: Enable matrix-based security and create administrators
  shell: "java -jar {{ jenkins_cli_jar }} -s http://{{ jenkins_listen_address  }}:{{ jenkins_port}}/ groovy {{ mktemp.stdout }}"
  register: jenkins_security
  ignore_errors: True

- name: Enable matrix-based security and create administrators
  shell: "java -jar {{ jenkins_cli_jar }} -s http://{{ jenkins_listen_address  }}:{{ jenkins_port}}/ groovy {{ mktemp.stdout }} {{ jenkins_admin_credentials }}"
  when: jenkins_security.stderr.find("hudson.security.AccessDeniedException2") != -1

- name: Remove Groovy script
  file:
    path: "{{ mktemp.stdout }}"
    state: absent

- name: Stop Jenkins (end of configure step)
  service:
    name: jenkins
    state: stopped
  when: not is_docker

