---


- name: Enable Yum repository
  get_url:
    url: "{{ jenkins_repo }}"
    dest: /etc/yum.repos.d/jenkins.repo
    force: yes

- name: Import RPM key
  rpm_key:
    key: "{{ jenkins_repo_key }}"
    state: present

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items: jenkins_packages

- name: Install required pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items: jenkins_pip_packages

- name: Configure Jenkins startup
  template:
    src: sysconfig.j2
    dest: /etc/sysconfig/jenkins

- name: Remove old upstart startup script
  file:
    path: /etc/init.d/jenkins
    state: absent

- name: Copy jenkins-env script
  copy:
    src: jenkins-env
    dest: /usr/lib/jenkins/jenkins-env
    mode: 0755

- name: Copy jenkins-env service file
  copy:
    src: jenkins-env.service
    dest: /usr/lib/systemd/system/jenkins-env.service

- name: Copy jenkins service file
  template:
    src: jenkins.service.j2
    dest: /usr/lib/systemd/system/jenkins.service

- name: Reload Systemd
  command: systemctl daemon-reload

- name: Create Jenkins auxiliary directory for holding JARs, scripts, etc
  file:
    path: "{{ jenkins_aux_dir }}"
    state: directory
    owner: root
    group: root

- name: Extract the jenkins_cli jarfile
  command: unzip -oj /usr/lib/jenkins/jenkins.war WEB-INF/jenkins-cli.jar -d /opt/jenkins/

- name: Create deploy user
  user:
    name: deploy
    state: present

- name: Create jenkins_jobs directory
  file:
    path: /home/deploy/jenkins_jobs
    state: directory
    owner: deploy

- name: Transfer jenkins-jobs configuration (missing token)
  copy:
    src: jenkins_jobs.ini
    dest: /home/deploy/jenkins_jobs.ini
    owner: deploy


