---


- name: Enable Yum repository
  get_url:
    url: "{{ jenkins_repo }}"
    dest: /etc/yum.repos.d/jenkins.repo
    force: yes

- name: Import RPM key
  rpm_key:
    key: "{{ jenkins_repo_key }}"
    state: present

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items: jenkins_packages

- name: Install required pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items: jenkins_pip_packages

- name: Remove old upstart startup script
  file:
    path: /etc/init.d/jenkins
    state: absent

- name: Copy jenkins-env script
  copy:
    src: jenkins-env
    dest: /usr/lib/jenkins/jenkins-env
    mode: 0755
  when: not is_docker

- name: Copy jenkins-env service file
  copy:
    src: jenkins-env.service
    dest: /usr/lib/systemd/system/jenkins-env.service
  when: not is_docker

- name: Copy jenkins service file
  template:
    src: jenkins.service.j2
    dest: /usr/lib/systemd/system/jenkins.service
  when: not is_docker

- name: Reload Systemd
  command: systemctl daemon-reload
  when: not is_docker

