---


- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always
    
- include: install.yml
  tags:
    - install
  
- include: configure.yml
  tags:
    - configure

- include: deploy.yml
  tags:
    - deploy

- include: test.yml
  tags:
    - test

